"""
numero = range(5) #[0, 1, 2, 3, 4,]
                  #

for i in numero:
    print(i, "hola")
"""


#tabla = range(11) 

#for a in tabla:
    #print(a*11)
    
    #print(a, "x 11 =", a * 11)








#tabla= range (1,13)

#for m in tabla:
    
numero = int(input("ingrese numero de la tabla"))

tabla= range (11)

for m in tabla:
    print(m*numero,)
    print(numero, "*",m, "=" numero*m)
    


    











